### ISSUE TITLE
Quick Conversion: Changes for base currencies apply for all currency pairs

### ISSUE THREAD

**Issue by shakeebularsalan** [ARK-Builders/ARK-Rate#66] opened 2023-12-15 05:57 UTC
Quick: Convert to currency added or deleted for one currency automatically applies to other currencies as well that is not correct.

e.g. Both KRW and GBP have base currencies USD and KZT. We delete base currency KZT from GBP, it disappears from KRW too.

**Comment by kirillt** [comment] 2023-12-15 14:36
Duplicate of #67

**Closed by kirillt** 2023-12-15 14:36 UTC
Labels: bug
